#pragma once

#include <d3d11.h>

namespace v8 { namespace directx { namespace internal {

const D3D11_CPU_ACCESS_FLAG kCPUAccessMappings[] = {
    D3D11_CPU_ACCESS_FLAG(0),
    D3D11_CPU_ACCESS_WRITE,
    D3D11_CPU_ACCESS_READ
};

const D3D11_USAGE kResourceUsageMappings[] = {
    D3D11_USAGE_DEFAULT,
    D3D11_USAGE_IMMUTABLE,
    D3D11_USAGE_DYNAMIC,
    D3D11_USAGE_STAGING
};

const D3D11_MAP kMapMapping[] = {
    D3D11_MAP_READ,
    D3D11_MAP_WRITE,
    D3D11_MAP_READ_WRITE,
    D3D11_MAP_WRITE_DISCARD,
    D3D11_MAP_WRITE_NO_OVERWRITE
};

const D3D11_PRIMITIVE_TOPOLOGY kTopologyMappings[] = {
    D3D11_PRIMITIVE_TOPOLOGY_UNDEFINED,
    D3D11_PRIMITIVE_TOPOLOGY_POINTLIST,
    D3D11_PRIMITIVE_TOPOLOGY_LINELIST,
    D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP,
    D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST,
    D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP,
    D3D11_PRIMITIVE_TOPOLOGY_LINELIST_ADJ,
    D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ,
    D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ,
    D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ
};

} // namespace internal
} // namespace directx
} // namespace v8
